[pytest]
markers =
    sanity: custom marker for quick sanity checks
    regression: custom marker for full regression suite
    smoke: custom marker for smoke tests
    stringtest: custom marker for string related tests